Flowpack:
  JobQueue:
    Common:
      queues:
        'neos-eventsourcing':
          className: Netlogix\EventSourcing\TestEssentials\Queue\SameProcessFakeQueue
          options:
            async: false
